"""Add new field to User

Revision ID: 3356b6b0b5a6
Revises: 
Create Date: 2023-12-30 13:24:24.250618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3356b6b0b5a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('refresh_token')

    # ### end Alembic commands ###
